FROM node:17-slim as BUILDER
WORKDIR /usr/src/app
COPY web-dapp web-dapp
WORKDIR /usr/src/app/web-dapp
ARG WS_URI
RUN yarn build

FROM nginx:alpine

EXPOSE 80
COPY --from=BUILDER /usr/src/app/web-dapp/build /usr/share/nginx/html
